version: '3.6'
services:
  graphql-engine:
    image: hasura/graphql-engine:v2.0.9
    ports:
    - "8080:8080"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:password@192.168.1.21:5432/hasura
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:password@192.168.1.21:5432/testing
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      
      HASURA_GRAPHQL_ADMIN_SECRET: password

      HASURA_GRAPHQL_JWT_SECRET: '{
        "type": "HS256",
        "key": "a2755884920784e37e766a144dd3ba7877803add64437778b2656ad6bc19004a"
      }'
volumes:
  db_data:

